id: vendor.example.integration
name: Example Integration
version: 0.1.0
category: generic
min_core_version: "0.9.0"

schema:
  connection:
    type: object
    required: [endpoint]
    properties:
      endpoint:
        type: string
        format: uri
        title: API endpoint
      api_token:
        type: string
        title: API Token
        secret: true
      verify_tls:
        type: boolean
        default: true

defaults:
  http:
    timeout_s: 5
    retries: 2
    backoff_ms_start: 250
    verify_tls: true
  heartbeat_interval_s: 120

test:
  method: http
  http:
    request:
      method: GET
      path: /health
    success_when: "status in [200,204]"

capabilities:
  - id: notify.send
    verbs: [post]
    targets: [event]
    dry_run: optional

discovery:
  implements: inventory.list
  interval_s: 600

errors: {}