id: walnut.example.http-pinger
name: HTTP Pinger (Example)
version: 0.1.0
category: generic
min_core_version: "0.9.0"

schema:
  connection:
    type: object
    required: [endpoint]
    properties:
      endpoint: { type: string, format: uri, title: Base URL }
      auth_header: { type: string, secret: true, title: Optional Auth Header }
      verify_tls: { type: boolean, default: true }

defaults:
  http:
    timeout_s: 5
    retries: 2
    backoff_ms_start: 250
    verify_tls: true
  heartbeat_interval_s: 120

test:
  method: http
  http:
    request:
      method: GET
      path: /ping
    success_when: "status == 200"

capabilities:
  - id: power.control
    verbs: [off, on, cycle]
    targets: [host]
    dry_run: required
  - id: notify.send
    verbs: [post]
    targets: [event]
    dry_run: optional

discovery:
  implements: inventory.list
  interval_s: 600